{{- if .Values.secrets.enabled }}
{{- $baseName := .Values.global.base_name -}}
{{- $argocdNamespace := .Values.global.argocd_namespace -}}
{{- range .Values.secrets.items }}
{{- $secretName := ternary (printf "%s-%s" $baseName .name) .name $.Values.group_service.enabled }}
{{- $secretSuffix := "-secret" }}
{{- $endsWithSecret := hasSuffix $secretSuffix $secretName }}
{{- $finalName := ternary $secretName (printf "%s%s" $secretName $secretSuffix) $endsWithSecret }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $finalName }}
  labels:
    {{- $trimmedName := trimSuffix "-secret" $secretName }}
    app: {{ $trimmedName }}
    app.kubernetes.io/part-of: {{ $baseName }}
    app.kubernetes.io/component: secrets
type: Opaque
data:
  {{- range .keys }}
  {{ . }}: "<path:{{ $argocdNamespace }}/data/{{ $finalName }}#{{ . }} | base64encode>"
  {{- end }}
---
{{- end }}
{{- end }}
