apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
spec:
  destination:
    name: ""
    namespace: namespace_example
    server: "https://kubernetes.default.svc"
  source:
    path: charts
    repoURL: "example_git_link"
    targetRevision: main
    plugin:
      env:
        - name: VAULT_ADDR
          value: "https://vault.eco.svc:8200"
        - name: HELM_VALUES_FILE
          value: ./values-prod.yaml
  project: namespace_example
  ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/initContainers/0/image
