apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: name_app_argocd
spec:
  destination:
    name: ""
    namespace: namespace_example
    server: "https://kubernetes.default.svc"
  source:
    path: charts
    repoURL: "https://git.git"
    targetRevision: main
    helm:
      valueFiles:
        - ./values-prod.yaml
  project: namespace_example
  ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/initContainers/0/image
